version: '0.1'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/rss_feeder/:/app/
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 12345
    env_file:
      - .env
    ports:
      - 12345:12345
    depends_on:
      - db

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
    postgres_data:

