[tool.basedpyright]
include = ["app"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

# reportMissingImports = true
# reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"
# reportGeneralTypeIssues = false

# basedpyright errors and warnings
reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportUnknownVariableType = "warning"
reportUnknownMemberType = "warning"
reportAny = "warning"

executionEnvironments = [
  { root = "web" }
]
